# Generated by Django 5.1 on 2024-09-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('image', models.ImageField(upload_to='profiles')),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
