# Generated by Django 5.1 on 2024-09-01 09:29

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='profiles'),
        ),
    ]
